# This file is machine-generated - editing it directly is not advised

[[Format]]
git-tree-sha1 = "f7fbd4f9475e9520c37dfa5476a11fb9d933044d"
uuid = "1fa38f19-a742-5d3f-a2b9-30dd87b9d5f8"
version = "1.3.0"
